apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopsbatches.mycustombatch.com # plural.name-of-crd.group
spec:
  group: mycustombatch.com
  scope: Namespaced
  names:
    kind: DevopsBatch    # name of our custom resource
    plural: devopsbatches  # must be plural, should be lowercase
    singular: devopsbatch  # must be singular, should be lowercase
    shortNames:
    - devb
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "name of the batch job"
              duration:
                type: string
                description: "duration of the batch job"
              mode:
                type: string
                description: "mode of the batch job, Live/Recorded"
              platform:
                type: string
                description: "platform of the batch job, YouTube/Vimeo"

             



