apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: nginx
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: rahuljngr/notes-app-k8s
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi" # minimum memory required 128MB
            cpu: "100m" # minimum cpu required 100MB
          limits:
            memory: "256Mi" # maximum memory allowed 256MB
            cpu: "200m" # maximum cpu allowed 200MB
        livenessProbe: # liveness probe
          httpGet:
              path: /
              port: 8000
        
