apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi" # minimum memory required 128MB
            cpu: "100m" # minimum cpu required 100MB
          limits:
            memory: "256Mi" # maximum memory allowed 256MB
            cpu: "200m" # maximum cpu allowed 200MB