kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: apache
  name: apache-manager
rules:
- apiGroups: ["","apps","rbac.authorization.k8s.io", "batch"] # "" -> v1 group , "apps" -> workload group, "rbac.authorization.k8s.io" -> rbac group, "batch" -> cronjob, job
  resources: ["pods","services","deployments"]
  verbs: ["get","apply","delete","watch","create","patch"] 