kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache
spec:
  targetRef: # imp, what we want to scal like pods, deployments, statefulsets, replicasets
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  
  updatePolicy:
    updateMode: "Auto" # Auto, Off, Initial